---
- name: CentralRouter
  hosts: all
  become: true
  tasks:
    - name: Epel Install
      yum:
       name: epel-release
       state: latest
    - name: install Services
      yum:
        name:
        - openvpn
        - iperf3
        - vim 
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
    - name: reboot
      ansible.builtin.reboot:
        reboot_timeout: 3600     

- name: Server1
  hosts: server
  become: true
  tasks:
   
    - name: static key
      copy:
        src: conf/static.key
        dest: /etc/openvpn/static.key
        owner: root
        group: root
        mode: 644   
    - name: server config
      copy:
        src: conf/server.conf
        dest: /etc/openvpn/server.conf
        owner: root
        group: root
        mode: 644   
    - name: systemd unit file
      copy:
        src: conf/openvpn@.service
        dest: /etc/systemd/system/openvpn@.service
        owner: root
        group: root
        mode: 644   

- name: Client
  hosts: client
  become: true
  tasks:
    - name: static key
      copy:
        src: conf/static.key
        dest: /etc/openvpn/static.key
        owner: root
        group: root
        mode: 644
    - name: client config
      copy:
        src: conf/client.conf
        dest: /etc/openvpn/server.conf
        owner: root
        group: root
        mode: 644
    - name: systemd unit file
      copy:
        src: conf/openvpn@.service
        dest: /etc/systemd/system/openvpn@.service
        owner: root
        group: root
        mode: 644